kind: pipeline
name: default

steps:
- name: build image
  image: plugins/docker
  settings:
    repo: mazzolino/docker-riot-web
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
